# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSEu5qN2NLDABPlfK3XReOEJ2X1ZCqyjmBVeILs90mt8rO_8wpsHtWAHqkm', max_length=2000),
            preserve_default=False,
        ),
    ]
